### ISSUE TITLE
Compilation error with Igor Pro 9

### ISSUE THREAD

**Issue by damianjwilliams** [SilverLabUCL/NeuroMatic#8]
I've just started using Igor Pro version 9 (9.0.0.10 (Build 37840)) and Neuromatic v3 and I'm getting a bunch of Duplicate Case errors when Neuromatic is compiling. The first one to appear is: 

Function Compilation Error 
Duplicate Case
Error in NM_ImportAxograph.ipf:CheckAxoUnits
case "(S)":

![Compilation_error](https://user-images.githubusercontent.com/18335331/133320994-0fdff1e3-ed57-4903-979b-2d3726e4ae58.png)

and there are a bunch more similar errors. Any idea how to resolve this?

**Comment by jasonsethrothman** [comment]
hi Damian

these are minor bugs that i fixed. you can download updated version from NM website:

http://www.neuromatic.thinkrandom.com/NMInstall.html

i will update GitHub code tomorrow.

best wishes

Jason

**Comment by damianjwilliams** [comment]
Hi Jason,

That works great. Thanks for your quick response. 

All the best,

Damian
